### ISSUE TITLE
URL not shown because there is an error with Javascript...

### ISSUE THREAD

**Issue by kitkatdafu** [Isu21842/unique-turker-2#2]
This message still appears when I am testing the my HIT in the sandbox, as a worker. I am pretty sure that Javascript and Cookies have been enabled for MTurk. Do you have any idea why this happens?

Thank you in advance!

**Comment by isaiasghezae** [comment]
Thank you for the note! When creating this, I never tested it using the Sandbox so not sure if there is something idiosyncratic about the Sandbox that makes it such that this error message still appears. Could you try actually posting the HIT for $0.01 (the minimum amount) and, ideally, set a custom qualification on the HIT such that only your worker account can access the HIT?

This is how I tested the app out myself and it worked (i.e., myself and other workers can access the HIT only once). I'd be curious if this didn't end up working for you, so please let me know how it goes.

**Comment by kitkatdafu** [comment]
I have tried to post the HIT to the real MTurk. Although I do not have a verified worker account in order to accept the HIT, I am able to see the text

> The link will appear here only if you accept this HIT.

So I think the Javascript is working. Perhaps the Sandbox is doing something different.

**Comment by isaiasghezae** [comment]
Yes, this is exactly what you/the worker should be seeing *before* the HIT has been accepted. Once the HIT is accepted, they will either be shown the survey link or (if they've already accepted the same HIT) the custom message stating to return the HIT since they have previously accepted it.

Since the message you received sounds right, I'll go ahead and close this issue. Thanks again for the note!
